name: Deploy to Render

on:
  push:
    branches:
      - deployment  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Deploy to Render
      env:
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        BACKEND_SRV: ${{ secrets.BACKEND_SRV }}
        FRONTEND_SRV: ${{ secrets.FRONTEND_SRV }}
      run: |
        chmod +x ./deploy.sh
        ./deploy.sh
